from random import seed, randrange

template = r'''
// automatically generated by Python's random number gen.

const uint64_t zobrist_array_[] = {{
{zints}
}};

// end automatically generated random numbers.
'''

def main(args):
    seed(args.s)
    randints = []
    for i in range(args.num):
        while True:
            rint = randrange(1, 2**64)
            if all(rint != ii for ii in randints):
                randints.append(rint)
                break
    randint_strs = ['\t%#xULL' % ri for ri in randints]
    allints = ',\n'.join(randint_strs)
    print template.format(zints=allints)


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser('Generate zobrist random integers.')
    parser.add_argument('num', type=int, help='number of integers to generate')
    parser.add_argument('-s', type=int, default=2718281828459045L,
                        help='random number seed.')
    args = parser.parse_args()
    main(args)
